The task request by the user is the following:
{task}

The actions already executed are the following:
{history}

The additional instructions for this step are the following:
{instructions}

You must answer using a properly json output containing:
- a summary of insight you learned in the previous step if any
- the action you want to execute next
- your reasoning to pick this next action
- if this action is final

{format}